### ISSUE TITLE
Blocking Google Analytics breaks shared pages

### ISSUE THREAD

**Issue by TormundsMember** [stolksdorf/homebrewery#88]
**Browser Type/Version**: Google Chrome 49.0.2623.112

**Operating System**: Win10

**Issue Description**: I can access the main page and the create page normally, but if I want to open a page somebody else shared, the page doesn't load.

The reason behind this: I'm running AdBlock, which blocks google analytics. It seems like your code is structured in such a way, where the whole code stops working, should it turn out that google analytics wasn't loaded in. After disabling my Adblock for your domain, analytics loaded the way it should and your page did work as intended.

The same will probably happen with apps like Ghostery, which blocks tracing services (like google analytics or the facebook thingy)

**Comment by stolksdorf** [comment]
Looks like a pretty easy fix. I'll move the analytics code out of the header. Strange that this is only happening to you on the share page, as the analytics code is loaded in the exact same fashion for all pages.

I also can not replicate your issue after installing Adblock (I use uBlock Origin normally). Can you link me to the exact extension you are using to I can try and replicate? Thanks!

**Comment by TormundsMember** [comment]
Sure! Would be the one from https://adblockplus.org/

chrome webstore page: https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb

**Comment by stolksdorf** [comment]
Sorry for the slow response. I think I fixed it. Could you try to replicate it on the new version on [staging](http://natural-crit-staging.herokuapp.com/homebrew/share/rktewxrf) ?

**Comment by TormundsMember** [comment]
No problem mate

http://imgur.com/a/V3aaR

Seems like the issue still persists, might be best just to note on the frontpage of your app that "disabling adblock might fix the issue"

**Comment by stolksdorf** [comment]
I can, but I've built pages like this before and adblock hasn't been an issue. It's not needed for it to run, I just like having the metrics. 

I'll take another peek at it today.

**Comment by stolksdorf** [comment]
I can not replicate this. I've even tried uninstalling chrome and reinstalling it then adblock, and every page still loads fine. Researched the issue a bunch, barely anyone is having this issue. However an older version of adblock seemed to choke if you didn't specify `http`. I've updated that and pushed it to staging. 

If you are still having this issue, I suggest updating your version of adblock to see if it fixes it.

**Comment by CultistO** [comment]
I am also having this issue. I am using Adblock **Plus** however, perhaps that is relevant.
I do not have to disable the extension entirely, as disabling it for the site is sufficient.

**Comment by TormundsMember** [comment]
@CultistO Should have specified, I'm also running Adblock Plus, but then again, I provided a link to both the website and the chrome addon story to ABP

**Comment by stolksdorf** [comment]
If there is any update on this issue, please reopen it. But I'm going to close this.
